version: "3"

services:
  rasa:
    build:
      context: .
    env_file: .env
    volumes:
      - models:/app/models
    expose:
      - 5002

  caddy:
    image: caddy
    command: caddy reverse-proxy --from ${DNS} --to rasa:5002
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  models:
  caddy_data:
  caddy_config:
